/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package tambahan_it;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventory.DlgCariKonversi;
import inventory.DlgCariObat;
import inventory.DlgCariObat2;
import inventory.DlgCariObat3;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import laporan.DlgPenyakit;
import laporan.DlgICD9;

/**
 *
 * @author perpustakaan
 */
public class DlgInputGrouperSementara extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private DlgPenyakit icd10=new DlgPenyakit(null,true);
    private DlgICD9 icd9=new DlgICD9(null,true);

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgInputGrouperSementara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
        //TCatatan.setText(TCatatan); 
//        TrfGrouper.setLineWrap(true);
//        TrfGrouper.setWrapStyleWord(true);
        
        
        icd10.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(icd10.getTabel().getSelectedRow()!= -1){
                    KdIcd10.setText(icd10.getTabel().getValueAt(icd10.getTabel().getSelectedRow(),1).toString());
                    NmIcd10.setText(icd10.getTabel().getValueAt(icd10.getTabel().getSelectedRow(),2).toString());
                    NmIcd10.requestFocus();
                }
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        icd9.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(icd9.getTabel().getSelectedRow()!= -1){
                    KdIcd9.setText(icd9.getTabel().getValueAt(icd9.getTabel().getSelectedRow(),1).toString());
                    NmIcd9.setText(icd9.getTabel().getValueAt(icd9.getTabel().getSelectedRow(),2).toString());
                    NmIcd9.requestFocus();
                }
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        jLabel3 = new widget.Label();
        TNoRM = new widget.TextBox();
        TPasien = new widget.TextBox();
        jLabel9 = new widget.Label();
        TNoRw = new widget.TextBox();
        jLabel10 = new widget.Label();
        jLabel11 = new widget.Label();
        KdIcd10 = new widget.TextBox();
        KdIcd9 = new widget.TextBox();
        NmIcd10 = new widget.TextBox();
        NmIcd9 = new widget.TextBox();
        TrfGrouper = new widget.TextBox();
        btnIcd10 = new widget.Button();
        btnIcd9 = new widget.Button();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Input Tarif Grouping sementara ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput.setLayout(null);

        jLabel3.setText("No. Rawat :");
        jLabel3.setName("jLabel3"); // NOI18N
        FormInput.add(jLabel3);
        jLabel3.setBounds(0, 10, 65, 23);

        TNoRM.setEditable(false);
        TNoRM.setHighlighter(null);
        TNoRM.setName("TNoRM"); // NOI18N
        FormInput.add(TNoRM);
        TNoRM.setBounds(220, 10, 130, 23);

        TPasien.setEditable(false);
        TPasien.setHighlighter(null);
        TPasien.setName("TPasien"); // NOI18N
        TPasien.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(TPasien);
        TPasien.setBounds(350, 10, 486, 23);

        jLabel9.setText("Tarif Grouper :");
        jLabel9.setName("jLabel9"); // NOI18N
        FormInput.add(jLabel9);
        jLabel9.setBounds(0, 120, 80, 23);

        TNoRw.setEditable(false);
        TNoRw.setHighlighter(null);
        TNoRw.setName("TNoRw"); // NOI18N
        FormInput.add(TNoRw);
        TNoRw.setBounds(70, 10, 150, 24);

        jLabel10.setText("ICD 10 :");
        jLabel10.setName("jLabel10"); // NOI18N
        FormInput.add(jLabel10);
        jLabel10.setBounds(10, 50, 65, 23);

        jLabel11.setText("ICD 9 :");
        jLabel11.setName("jLabel11"); // NOI18N
        FormInput.add(jLabel11);
        jLabel11.setBounds(10, 80, 65, 23);

        KdIcd10.setEditable(false);
        KdIcd10.setHighlighter(null);
        KdIcd10.setName("KdIcd10"); // NOI18N
        FormInput.add(KdIcd10);
        KdIcd10.setBounds(80, 50, 70, 24);

        KdIcd9.setEditable(false);
        KdIcd9.setHighlighter(null);
        KdIcd9.setName("KdIcd9"); // NOI18N
        FormInput.add(KdIcd9);
        KdIcd9.setBounds(80, 80, 70, 24);

        NmIcd10.setEditable(false);
        NmIcd10.setHighlighter(null);
        NmIcd10.setName("NmIcd10"); // NOI18N
        FormInput.add(NmIcd10);
        NmIcd10.setBounds(150, 50, 350, 24);

        NmIcd9.setEditable(false);
        NmIcd9.setHighlighter(null);
        NmIcd9.setName("NmIcd9"); // NOI18N
        FormInput.add(NmIcd9);
        NmIcd9.setBounds(150, 80, 350, 24);

        TrfGrouper.setHighlighter(null);
        TrfGrouper.setName("TrfGrouper"); // NOI18N
        FormInput.add(TrfGrouper);
        TrfGrouper.setBounds(80, 120, 420, 24);

        btnIcd10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnIcd10.setMnemonic('1');
        btnIcd10.setToolTipText("Alt+1");
        btnIcd10.setName("btnIcd10"); // NOI18N
        btnIcd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcd10ActionPerformed(evt);
            }
        });
        btnIcd10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIcd10KeyPressed(evt);
            }
        });
        FormInput.add(btnIcd10);
        btnIcd10.setBounds(510, 50, 28, 23);

        btnIcd9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnIcd9.setMnemonic('1');
        btnIcd9.setToolTipText("Alt+1");
        btnIcd9.setName("btnIcd9"); // NOI18N
        btnIcd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcd9ActionPerformed(evt);
            }
        });
        btnIcd9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIcd9KeyPressed(evt);
            }
        });
        FormInput.add(btnIcd9);
        btnIcd9.setBounds(510, 80, 32, 22);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnEdit);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if(TNoRw.getText().trim().equals("")||TPasien.getText().trim().equals("")){
            Valid.textKosong(TNoRM,"No.Rawat");
        }else if(TrfGrouper.getText().trim().equals("")){
            Valid.textKosong(TrfGrouper,"Tarif Grouper");
        }else{          
            Sequel.menyimpan3("pku_grouper_sementara","?,?,?,?,?,?",6,new String[]{TNoRw.getText(),KdIcd10.getText(),NmIcd10.getText(),KdIcd9.getText(),NmIcd9.getText(),TrfGrouper.getText()},"no_rawat=?","kd_icd10=?,nm_icd10=?,kd_icd9=?,nm_icd9=?,tarif=?",6,new String[]{KdIcd10.getText(),NmIcd10.getText(),KdIcd9.getText(),NmIcd9.getText(),TrfGrouper.getText(),TNoRw.getText()});
            BtnKeluarActionPerformed(evt);        
        }  
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,TrfGrouper,BtnKeluar);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
       Sequel.meghapus2("pku_grouper_sementara","no_rawat",TNoRw.getText());
       BtnKeluarActionPerformed(evt);       
}//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        
}//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
    if(TNoRw.getText().trim().equals("")||TPasien.getText().trim().equals("")){
        Valid.textKosong(TNoRM,"No.Rawat");
    }else if(TrfGrouper.getText().trim().equals("")){
        Valid.textKosong(TrfGrouper,"Catatan");
    }else{  
        Sequel.mengedit2("pku_grouper_sementara","no_rawat=?","kd_icd10=?,nm_icd10=?,kd_icd9=?,nm_icd9=?,tarif=?",6,new String[]{
            KdIcd10.getText(),NmIcd10.getText(),KdIcd9.getText(),NmIcd9.getText(),TrfGrouper.getText(),TNoRw.getText()
        });
        BtnKeluarActionPerformed(evt);
    }
}//GEN-LAST:event_BtnEditActionPerformed

private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnEditActionPerformed(null);
        }
}//GEN-LAST:event_BtnEditKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TrfGrouper.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void btnIcd10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcd10ActionPerformed
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//            DlgPenyakit icd10=new DlgPenyakit(null,true);
            icd10.setSize(720,330);
            icd10.setLocationRelativeTo(internalFrame1);
            icd10.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
            
//            icd10.addWindowListener(new WindowListener() {
//            @Override
//            public void windowOpened(WindowEvent e) {}
//            @Override
//            public void windowClosing(WindowEvent e) {}
//            @Override
//            public void windowClosed(WindowEvent e) {
//                if(icd10.getTabel().getSelectedRow()!= -1){
//                    KdIcd10.setText(icd10.getTabel().getValueAt(icd10.getTabel().getSelectedRow(),1).toString());
//                    NmIcd10.setText(icd10.getTabel().getValueAt(icd10.getTabel().getSelectedRow(),2).toString());
//                    NmIcd10.requestFocus();
//                }
//            }
//            @Override
//            public void windowIconified(WindowEvent e) {}
//            @Override
//            public void windowDeiconified(WindowEvent e) {}
//            @Override
//            public void windowActivated(WindowEvent e) {}
//            @Override
//            public void windowDeactivated(WindowEvent e) {}
//        });
        
    }//GEN-LAST:event_btnIcd10ActionPerformed

    private void btnIcd10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIcd10KeyPressed
        
    }//GEN-LAST:event_btnIcd10KeyPressed

    private void btnIcd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcd9ActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//            DlgPenyakit icd10=new DlgPenyakit(null,true);
        icd9.setSize(720,330);
        icd9.setLocationRelativeTo(internalFrame1);
        icd9.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());

    }//GEN-LAST:event_btnIcd9ActionPerformed

    private void btnIcd9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIcd9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIcd9KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgInputGrouperSementara dialog = new DlgInputGrouperSementara(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.PanelBiasa FormInput;
    private widget.TextBox KdIcd10;
    private widget.TextBox KdIcd9;
    private widget.TextBox NmIcd10;
    private widget.TextBox NmIcd9;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRw;
    private widget.TextBox TPasien;
    private widget.TextBox TrfGrouper;
    private widget.Button btnIcd10;
    private widget.Button btnIcd9;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel3;
    private widget.Label jLabel9;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
    }

    public void setNoRm(String norm, String norwt) {
        TNoRM.setText(norm);  
        TNoRw.setText(norwt);
        isPsien();   
        tampil();
              
    }
    
    
    public void isCek(){
        BtnSimpan.setEnabled(true);
        BtnHapus.setEnabled(true);
        BtnEdit.setEnabled(true);
       
        
    }

    private void tampil() {
        try {
            ps=koneksi.prepareStatement(

            "SELECT pku_grouper_sementara.kd_icd10,pku_grouper_sementara.nm_icd10,pku_grouper_sementara.kd_icd9,pku_grouper_sementara.nm_icd9,pku_grouper_sementara.tarif FROM pku_grouper_sementara where pku_grouper_sementara.no_rawat=? LIMIT 1");
                         
            try {
                ps.setString(1,TNoRw.getText());
                rs=ps.executeQuery();
                if(rs.next()){
                    KdIcd10.setText(rs.getString("kd_icd10"));
                    NmIcd10.setText(rs.getString("nm_icd10"));
                    KdIcd9.setText(rs.getString("kd_icd9"));
                    NmIcd9.setText(rs.getString("nm_icd9"));
                    TrfGrouper.setText(rs.getString("tarif"));                  
                    
                }
            } catch (Exception e) {
                System.out.println("Notif : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : "+e);
        }
    }

}
